### ISSUE TITLE
arc42 template

### ISSUE THREAD

**Issue by cidinene** [pglez82/asw2122_0#5]
Hi, 
This repository is not using custom [ArqSw arc42 template](https://github.com/pglez82/radarin_0/tree/master/webapp/docs), since not  Table of Contents , Software Archictecture Logo.  I miss some explications included in every sections too. 
Maybe is better change to custom version?

**Comment by labra** [comment]
In #6 , I changed index.adoc to include the table of contents.

**Comment by cidinene** [comment]
https://github.com/pglez82/radarin_0/blob/master/webapp/docs/06_runtime_view.adoc es diferente

**Comment by cidinene** [comment]
en el https://github.com/pglez82/asw2122_0/blob/master/docs/src/08_concepts.adoc no se incluye el modelo de dominio

**Comment by pglez82** [comment]
Restored old template with all the diagrams and images.
